### ISSUE TITLE
GBDTNameDivider() occurs FileNotFoundError

### ISSUE THREAD

**Issue by muto-jo** [rskmoi/namedivider-python#24] opened 2022-06-29 15:42 UTC
GBDTNameDivider occurs FileNotFoundError in environment that user cache directory (/Users/"user_name"/.cache) is not exist.

I paste traceback message when I do sample code and occurs error.

```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
/var/folders/cl/wm2yh_cj509fjnj8d5nw0vtw0000gn/T/ipykernel_12025/2559231275.py in <module>
      8 basic_divider = BasicNameDivider() # BasicNameDivider is fast but accuracy is 99.2%
      9 
---> 10 gbdt_divider = GBDTNameDivider() # GBDTNameDivider is slow but accuracy is 99.9%
     11 divided_name = gbdt_divider.divide_name("菅義偉")
     12 print(divided_name)

~/.pyenv/versions/anaconda3-2021.11/envs/ai_study/lib/python3.9/site-packages/namedivider/divider/gbdt_name_divider.py in __init__(self, config)
     21             config = GBDTNameDividerConfig()
     22         super().__init__(config=config)
---> 23         download_family_name_pickle_if_needed(config.path_family_names)
     24         download_gbdt_model_v1_if_needed(config.path_model)
     25         kanji_statistics_repository = KanjiStatisticsRepository(path_csv=config.path_csv)

~/.pyenv/versions/anaconda3-2021.11/envs/ai_study/lib/python3.9/site-packages/namedivider/util.py in download_family_name_pickle_if_needed(path)
     39     if path.exists():
     40         return None
---> 41     DEFAULT_CACHE_DIR.mkdir(exist_ok=True)
     42     print("Download FamilyNameRepository from GitHub...")
     43     content = requests.get(FAMILY_NAME_REPOSITORY_URL).content

~/.pyenv/versions/anaconda3-2021.11/envs/ai_study/lib/python3.9/pathlib.py in mkdir(self, mode, parents, exist_ok)
   1321         """
   1322         try:
-> 1323             self._accessor.mkdir(self, mode)
   1324         except FileNotFoundError:
   1325             if not parents or self.parent == self:

FileNotFoundError: [Errno 2] No such file or directory: '/Users/"user_name"/.cache/namedivider-python'
```

I tried to fix.
namedivider/util.py L.41 changes "DEFAULT_CACHE_DIR.mkdir(exist_ok=True)" -> "DEFAULT_CACHE_DIR.mkdir(exist_ok=True, parents=True)".
But, error cannot fix...

I make /Users/"user_name"/.cache directory by mkdir command. This error don't occurs.

I fixed this problem by myself, but, other user may gets same error and this issue has possibility of useful for you. So, I will report this error in issue.

**Comment by rskmoi** [comment] 2023-06-15 07:04
Thank you for your report.
I have confirmed that the error occurs on Windows because the .cache directory does not exist on Windows.
I have fixed this in #27 and improved the GitHub Actions so that the test is performed on Windows/Mac as well.
This has been fixed in v0.2.1 released today.

> "DEFAULT_CACHE_DIR.mkdir(exist_ok=True, parents=True)".
> But, error cannot be fixed...

I don't know the reason for the above, sorry.

This will close this issue, but if you continue to experience problems, please contact me again.

**Closed by rskmoi** 2023-06-15 07:04 UTC
